name: Deploy Vue to Pages
on:
  push:
    branches: [main] # Trigger on pushes to main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist # Matches your Vue build output folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
